apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mmkv-writer
  namespace: default
  labels:
    app: mmkv-writer
spec:
  selector:
    matchLabels:
      name: mmkv-writer
  template:
    metadata:
      labels:
        name: mmkv-writer
    spec:
      containers:
        - name: mmkv-writer
          image: localhost:5001/mmkv-go:latest
          args: ["./mmkv-test", "-m", "set", "-d", "/tmp/mmkv"]
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: tmpmmkv
              mountPath: /tmp/mmkv
      # it may be desirable to set a high priority class to ensure that a DaemonSet Pod
      # preempts running Pods
      # priorityClassName: important
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tmpmmkv
          hostPath:
            path: /tmp/mmkv-k8s
            type: DirectoryOrCreate
